project:
  type: website
  output-dir: docs

website:
  title: "Explorer for Kinome Profiling Data"
  sidebar: false

format:
  html:
    theme: cosmo
    toc: false
    embed-resources: true
    page-layout: full
